services:
  banco:
    image: postgres:17
    container_name: almoxe-postgres
    environment:
      POSTGRES_DB: almoxe_db
      POSTGRES_USER: almoxe_app
      POSTGRES_PASSWORD: senha_local_dev
    ports:
      - "5432:5432"
    volumes:
      - dados_postgres:/var/lib/postgresql/data

volumes:
  dados_postgres: