spring.application.name=almoxe-api

spring.datasource.url=jdbc:postgresql://localhost:5432/almoxe_db
spring.datasource.username=almoxe_app
spring.datasource.password=senha_local_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

almoxe.storage.fotos-dir=./uploads/fotos
