spring.application.name=almoxe-api

spring.datasource.url=jdbc:postgresql://localhost:5432/almoxe_db
spring.datasource.username=almoxe_app
spring.datasource.password=senha_local_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
