spring.application.name=almoxe-api

spring.datasource.url=jdbc:postgresql://localhost:5432/almoxe_db
spring.datasource.username=almoxe_app
spring.datasource.password=senha_local_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

almoxe.storage.fotos-dir=./uploads/fotos

# Secret de DEV (HMAC-256). Em produção, externalizar via variável de ambiente.
almoxe.security.jwt.secret=2Qu8qkYJKeVyzu07UqOCryJBUn/5U6AA+0mvtASTZ0E=
almoxe.security.jwt.expiration-ms=86400000

logging.level.com.almoxe=INFO
